### ISSUE TITLE
["BUG"]The plugin could not be activated because it caused an error that could not be prevented.

### ISSUE THREAD

**Issue by anonim-01** [openedx/openedx-wordpress-ecommerce#62] opened 2023-11-12 02:39 UTC
**Describe the bug**
![hata](https://github.com/openedx/openedx-wordpress-ecommerce/assets/119737658/b03fb956-146e-49bf-8281-37d2f4fdc881)

**The plugin could not be activated because it caused an error that could not be prevented.I get this error, it was added, but** 

`[url=https://www.hizliresim.com/nr1qvdg][img]https://i.hizliresim.com/nr1qvdg.jpg[/img][/url]`

**Comment by MaferMazu** [comment] 2023-11-14 18:19
Hello, @anonim-01, thanks for reporting the bug.

Message in WordPress that @anonim-01 reports: "The plugin could not be activated because it caused an unavoidable error."

Could you let me know if you installed it from the ZIP file in the release? 
![Screenshot from 2023-11-09 15-14-12](https://raw.githubusercontent.com/openedx/openedx-wordpress-ecommerce/e6642cb04bb4f3df10554b4217e64839f9ed5ac5/docs/source/_images/zip-from-release.png)

**Comment by MaferMazu** [comment] 2024-05-17 14:36
@anonim-01, please let me know if this still happens.

**Comment by felipemontoya** [comment] 2024-06-07 15:12
@anonim-01 Also it would be very helpful if you post the screenshot in english as the screenshot you provided is difficult to understand.

@MaferMazu given that this has been open without information from the reporter for quite a while, what do you think about having a 6 months deadline for closing reported issues without follow up?

**Comment by bmtcril** [comment] 2024-06-25 16:46
Hi, all. I was attempting to install this and ran into a similar error (possibly the same one). Here are my steps to reproduce:

- Run Wordpress 6.5.5 from the default Docker image
- Go through the usual install process for Wordpress
- Install WooComerce 9.0.2 from the WP Admin -> Plugins menu
- Download the openedx-wordpress-ecommerce-2.0.4.zip from the releases page here
- Go to WP Admin -> Plugins -> Add New Plugin -> Upload Plugin, upload the zip
- Get upload success message
- Activate plugin
- Error: "Plugin could not be activated because it triggered a fatal error."

Wordpress logs state:

`PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/includes/model/class-openedx-commerce-api-calls.php:14\nStack trace:\n#0 /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/includes/class-openedx-commerce.php(171): include_once()\n#1 /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/includes/class-openedx-commerce.php(74): OpenedX_Commerce\\Openedx_Commerce->load_dependencies()\n#2 /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/openedx-commerce.php(109): OpenedX_Commerce\\Openedx_Commerce->__construct()\n#3 /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/openedx-commerce.php(112): openedx_commerce_plugin_run()\n#4 /var/www/html/wp-admin/includes/plugin.php(2389): include_once('/var/www/html/w...')\n#5 /var/www/html/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape('openedx-wordpre...')\n#6 /var/www/html/wp-admin/plugins.php(60): activate_plugin('openedx-wordpre...', 'https://wordpre...', false)\n#7 {main}\n  thrown in /var/www/html/wp-content/plugins/openedx-wordpress-ecommerce-2.0.4/includes/model/class-openedx-commerce-api-calls.php on line 14, referer: https://wordpress.tutor-nightly-local.orb.local/wp-admin/update.php?action=upload-plugin`

And indeed there is no `commerce-2.0.4/vendor/autoload.php` file in that location.

<img width="652" alt="Screenshot 2024-06-25 at 12 44 13 PM" src="https://github.com/openedx/openedx-wordpress-ecommerce/assets/112640379/72d9bd0d-1a94-49c4-bd33-3eeb19fde4c3">

<img width="674" alt="Screenshot 2024-06-25 at 12 44 26 PM" src="https://github.com/openedx/openedx-wordpress-ecommerce/assets/112640379/69ba49e0-137b-41fa-b011-9327880fb397">

**Comment by bmtcril** [comment] 2024-06-25 18:48
I did also try to downgrade Wordpress to the 6.3.1 listed in the readme, but Woocommerce will no longer install on a version that old.

**Comment by MaferMazu** [comment] 2024-06-25 19:04
Hello @bmtcril, thanks for reporting this. I will take a look ASAP, but I think your report doesn't relate to the first one reported here. I believe it is associated with some recent changes I made to have a ZIP file only with the necessary files #76.

I will take a look and keep you posted. Thanks again for the report.

**Comment by MaferMazu** [comment] 2024-06-25 22:50
@bmtcril, I created this [ZIP file with the fix](https://github.com/eduNEXT/openedx-wordpress-ecommerce/releases/download/v2.0.3/openedx-commerce.zip), would you mind install and activate this version?

The formal PR is #82 

I am attentive to any feedback.

**Comment by bmtcril** [comment] 2024-06-26 18:26
Yep, that zip works for me. Thanks!

**Closed** 2024-06-26 19:23 UTC
Labels: bug, help wanted, waiting on author
